Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPractice.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContext : DbContext
    {
        public DatabaseContext()
            : base("name=DatabaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student> Students { get; set; }
    }
}

Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\91852\source\repos\MvcPractice\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Models/Student.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    }
}

Controllers/EmpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcPractice.Models;

namespace MvcPractice.Controllers
{
    public class EmpController : Controller
    {
        DatabaseContext db = new DatabaseContext();
        public ActionResult Add(int id=0)
        {
            ViewBag.vb = "Save";
            Student obj = new Student();
            if(id>0)
            {
                var data = db.Students.Where(x => x.Id == id).ToList();
                obj.Id = data[0].Id;
                obj.Name= data[0].Name;
                obj.Age = data[0].Age;
                ViewBag.vb = "Update";
            }
            return View(obj);
        }
        [HttpPost]
        public ActionResult Add(Student student)
        {
            if(student.Id>0)
            {
                db.Entry(student).State = System.Data.Entity.EntityState.Modified;
            }
            else
            {

            db.Students.Add(student);
            }
            db.SaveChanges();
            return RedirectToAction("Show");
        }
        public ActionResult Show()
        {
            return View(db.Students.ToList());
        }
        public ActionResult Delete(int id=0)
        {
            var data = db.Students.Find(id);
            db.Students.Remove(data);
            db.SaveChanges();
            return RedirectToAction("Show");
        }
    }
}

Views/Emp/Add.cshtml
@model MvcPractice.Models.Student
@{
    ViewBag.Title = "Add";
}

@using (Html.BeginForm("Add","Emp",FormMethod.Post)) {
<table>
    @Html.HiddenFor(x=>x.Id)
    <tr>
        <th>Name</th>
        <td>@Html.TextBoxFor(x => x.Name)</td>
    </tr>
    <tr>
        <th>Age</th>
        <td>@Html.TextBoxFor(x => x.Age)</td>
    </tr>
    <tr>
        
        <td><input type="submit" value="@ViewBag.vb"/></td>
    </tr>
</table>
}

Views/Emp/Show.cshtml
@model List<MvcPractice.Models.Student>
@{
    ViewBag.Title = "Show";
}

<h2>Show</h2>

<table border="1">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Age</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Age</td>
            <td>@Html.ActionLink("DeleteButton","Delete",new {id=item.Id })</td>
            <td>@Html.ActionLink("Edit","Add",new {id=item.Id })</td>

        </tr>
    }
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Add New Employee", "Add", "Emp", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>